using System;
using System.Collections.Generic;
using QuestFlag.Infrastructure.Domain.Enums;

namespace QuestFlag.Infrastructure.Domain.Entities;

public class UploadRecord
{
    public Guid Id { get; init; } = Guid.NewGuid();
    
    public Guid TenantId { get; init; }
    public Guid UserId { get; init; }
    
    // Original file name (e.g. data.csv)
    public string OriginalFileName { get; init; } = string.Empty;
    
    // Prefix generated by system: {tenantId}-{userId}-{taskName}-{OriginalFileName}
    public string StoredFileName { get; init; } = string.Empty;
    
    // The bucket or container name (tenant_slug)
    public string BucketName { get; init; } = string.Empty;
    
    // Object Key: {category}/{taskName}/{StoredFileName}
    public string ObjectKey { get; init; } = string.Empty;
    
    public string TaskName { get; init; } = string.Empty;
    public string Category { get; init; } = string.Empty; 
    public long SizeInBytes { get; init; }
    
    public string[] Tags { get; init; } = Array.Empty<string>();
    public Dictionary<string, string> ExtraData { get; init; } = new();
    
    public UploadStatus Status { get; set; } = UploadStatus.Pending;
    public string? ErrorMessage { get; set; }
    public int RetryCount { get; set; }
    
    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime? CompletedAtUtc { get; set; }

    // Soft delete feature
    public bool IsDeleted { get; set; } = false;
    public DateTime? DeletedAtUtc { get; set; }
    public string? DeletedByUserId { get; set; }
}
