name: qf-app-infra

services:
  # service-qf-infra:
  #   extra_hosts:
  #     - "localhost:host-gateway"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${INFRASTRUCTURE_SERVICES_HTTP_PORT}
  #     - ASPNETCORE_HTTPS_PORTS=${INFRASTRUCTURE_SERVICES_HTTPS_PORT}
  #     - Storage__MinioAccessKey=${STORAGE_MINIO_ACCESS_KEY}
  #     - Storage__MinioSecretKey=${STORAGE_MINIO_SECRET_KEY}
  #     - Storage__MinioEndpoint=${STORAGE_MINIO_ENDPOINT}
  #     - Kafka__BootstrapServers=${KAFKA_BOOTSTRAP_SERVERS}
  #     - ConnectionStrings__InfrastructureConnection=${INFRASTRUCTURE_CONNECTION_STRING}
  #     - ServiceUrls__PassportServices=${URL_PASSPORT_SERVICES}
  #     - ServiceUrls__InfraServices=${URL_INFRA_SERVICES}
  #     - ServiceUrls__InfraWebApp=${URL_INFRA_WEBAPP}
  #     - ServiceUrls__InfraWebAppHttp=http://localhost:${INFRA_WEBAPP_HTTP_PORT}
  #   ports:
  #     - "${INFRASTRUCTURE_SERVICES_HTTP_PORT}:${INFRASTRUCTURE_SERVICES_HTTP_PORT}"
  #     - "${INFRASTRUCTURE_SERVICES_HTTPS_PORT}:${INFRASTRUCTURE_SERVICES_HTTPS_PORT}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # app-qf-infra:
  #   extra_hosts:
  #     - "localhost:host-gateway"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${INFRA_WEBAPP_HTTP_PORT}
  #     - ASPNETCORE_HTTPS_PORTS=${INFRA_WEBAPP_HTTPS_PORT}
  #   ports:
  #     - "${INFRA_WEBAPP_HTTPS_PORT}:${INFRA_WEBAPP_HTTPS_PORT}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # app-qf-passport:
  #   extra_hosts:
  #     - "localhost:host-gateway"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${PASSPORT_WEBAPP_HTTP_PORT}
  #     - ASPNETCORE_HTTPS_PORTS=${PASSPORT_WEBAPP_HTTPS_PORT}
  #   ports:
  #     - "${PASSPORT_WEBAPP_HTTPS_PORT}:${PASSPORT_WEBAPP_HTTPS_PORT}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  # app-qf-passport-admin:
  #   extra_hosts:
  #     - "localhost:host-gateway"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ASPNETCORE_HTTP_PORTS=${PASSPORT_ADMINWEBAPP_HTTP_PORT}
  #     - ASPNETCORE_HTTPS_PORTS=${PASSPORT_ADMINWEBAPP_HTTPS_PORT}
  #   ports:
  #     - "${PASSPORT_ADMINWEBAPP_HTTPS_PORT}:${PASSPORT_ADMINWEBAPP_HTTPS_PORT}"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  infra-postgres:
    image: ${POSTGRES_IMAGE}
    container_name: infra-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Configs/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  infra-redis:
    image: ${REDIS_IMAGE}
    container_name: infra-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  infra-kafka:
    image: ${KAFKA_IMAGE}
    container_name: infra-kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://infra-kafka:${KAFKA_PORT}
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@infra-kafka:${KAFKA_CONTROLLER_PORT}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_QUORUM_VOTERS=1@infra-kafka:${KAFKA_CONTROLLER_PORT}
    volumes:
      - kafka_data:/bitnami/kafka

  infra-minio:
    image: ${MINIO_IMAGE}
    container_name: infra-minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

  infra-qdrant:
    image: ${QDRANT_IMAGE}
    container_name: infra-qdrant
    ports:
      - "${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage

  infra-etcd:
    image: ${ETCD_IMAGE}
    container_name: infra-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:${ETCD_CLIENT_PORT} -listen-client-urls http://0.0.0.0:${ETCD_CLIENT_PORT} --data-dir /etcd

  infra-milvus:
    image: ${MILVUS_IMAGE}
    container_name: infra-milvus
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: ${MILVUS_ETCD_ENDPOINTS}
      MINIO_ADDRESS: ${MILVUS_MINIO_ADDRESS}
      MINIO_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MILVUS_PORT}:${MILVUS_PORT}"
      - "${MILVUS_WEB_PORT}:${MILVUS_WEB_PORT}"
    depends_on:
      - infra-etcd
      - infra-minio
    volumes:
      - milvus_data:/var/lib/milvus

  infra-neo4j:
    image: ${NEO4J_IMAGE}
    container_name: infra-neo4j
    ports:
      - "${NEO4J_HTTP_PORT}:${NEO4J_HTTP_PORT}"
      - "${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data

  infra-otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE}
    container_name: infra-otel-collector
    command: [ "--config=/etc/otel-collector.yml" ]
    volumes:
      - ./Configs/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "${OTEL_COLLECTOR_GRPC_PORT}:${OTEL_COLLECTOR_GRPC_PORT}"
      - "${OTEL_COLLECTOR_HTTP_PORT}:${OTEL_COLLECTOR_HTTP_PORT}"
      - "${OTEL_COLLECTOR_METRICS_PORT}:${OTEL_COLLECTOR_METRICS_PORT}"

  infra-prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: infra-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  infra-grafana:
    image: ${GRAFANA_IMAGE}
    container_name: infra-grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana

  infra-loki:
    image: ${LOKI_IMAGE}
    container_name: infra-loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./Configs/loki.yml:/etc/loki/local-config.yml
      - loki_data:/loki

  infra-tempo:
    image: ${TEMPO_IMAGE}
    container_name: infra-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "${TEMPO_PORT}:${TEMPO_PORT}"
      - "${TEMPO_OTLP_GRPC_PORT}:${TEMPO_OTLP_GRPC_CONTAINER_PORT}" # otlp grpc
    volumes:
      - ./Configs/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo

  questflag.passport.services:
    depends_on:
      - infra-postgres
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${PASSPORT_SERVICES_HTTP_PORT}
      - ASPNETCORE_HTTPS_PORTS=${PASSPORT_SERVICES_HTTPS_PORT}
      - ConnectionStrings__PassportConnection=${PASSPORT_CONNECTION_STRING}
      - ServiceUrls__InfraWebApp=${URL_INFRA_WEBAPP}
      - ServiceUrls__InfraWebAppHttp=http://localhost:${INFRA_WEBAPP_HTTP_PORT}
      - ServiceUrls__PassportWebApp=${URL_PASSPORT_WEBAPP}
      - ServiceUrls__PassportAdminWebApp=${URL_PASSPORT_ADMIN_WEBAPP}
      - OpenIddictApplications__infra-webapp=${URL_INFRA_WEBAPP}
      - OpenIddictApplications__passport-webapp=${URL_PASSPORT_WEBAPP}
      - OpenIddictApplications__passport-admin=${URL_PASSPORT_ADMIN_WEBAPP}
    ports:
      - "${PASSPORT_SERVICES_HTTP_PORT}:${PASSPORT_SERVICES_HTTP_PORT}"
      - "${PASSPORT_SERVICES_HTTPS_PORT}:${PASSPORT_SERVICES_HTTPS_PORT}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  postgres_data:
  redis_data:
  kafka_data:
  minio_data:
  qdrant_data:
  etcd_data:
  milvus_data:
  neo4j_data:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:


