name: qf-app-infra

services:
  service-qf-infra:
    image: ${DOCKER_REGISTRY}${SERVICE_INFRA_IMAGE}
    build:
      context: .
      dockerfile: Infrastructure/QuestFlag.Infrastructure.Services/Dockerfile
  app-qf-passport:
    image: ${DOCKER_REGISTRY}${APP_PASSPORT_IMAGE}
    build:
      context: .
      dockerfile: Passport/QuestFlag.Passport.WebApp/QuestFlag.Passport.WebApp/Dockerfile
  app-qf-passport-admin:
    image: ${DOCKER_REGISTRY}${APP_PASSPORT_ADMIN_IMAGE}
    build:
      context: .
      dockerfile: Passport/QuestFlag.Passport.AdminWebApp/QuestFlag.Passport.AdminWebApp/Dockerfile

  questflag.passport.services:
    image: ${DOCKER_REGISTRY-}questflagpassportservices
    build:
      context: .
      dockerfile: Passport/QuestFlag.Passport.Services/Dockerfile

